services:
  ssh_a:
    hostname: ssh_a
    build:
      context: a
      dockerfile: ../Dockerfile 
      #args:
        #SSHD_CONFIG: sshd_config
        #AUTHORIZED_KEY: ssh/id_ed25519.pub
        #SSH_KEY_DIR: ssh/id_ed25519
    ports:
      - "2222:22"
    networks: 
      - internal
    volumes:
      - ./:/home/rta/build:ro
    
  ssh_b:
    hostname: ssh_b
    build:
      context: b
      dockerfile: ../Dockerfile 
      #args:
        #SSHD_CONFIG: sshd_config
        #AUTHORIZED_KEY: ssh/id_ed25519.pub
        #SSH_KEY_DIR: ssh/id_ed25519
    networks:
      - internal





networks:
  internal: {}
