services:
  ssh_a:
    hostname: ssh_a
    build:
      context: .
      dockerfile: ssh_a/bld.Dockerfile 
      args:
        SELF: ssh_a
    ports:
      - "2222:22"
    networks: 
      - ab
    #volumes: #Host all keys for debugging
    #  - ./:/home/rta/build:ro
    
  ssh_b:
    hostname: ssh_b
    build:
      context: .
      dockerfile: ssh_b/bld.Dockerfile 
      args:
        SELF: ssh_b
    
    networks:
      - ab
      - bc
  ssh_c:
    hostname: ssh_c
    build:
      context: .
      dockerfile: ssh_c/bld.Dockerfile
      args:
        SELF: ssh_c
    networks:
      - bc





networks:
  internal: {}
  ab: {}
  bc: {}
