services:
  ssh_a:
    hostname: ssh_a
    build:
      context: a
      dockerfile: bld.Dockerfile 
    command: /usr/sbin/sshd -D
    ports:
      - "2222:22"
    networks: 
      - internal
    volumes:
      - ./:/home/rta/build:ro
    
  ssh_b:
    hostname: ssh_b
    build:
      context: b
      dockerfile: bld.Dockerfile 
    command: /usr/sbin/sshd -D
    networks:
      - internal





networks:
  internal: {}
