services:
  ssh_a:
    hostname: ssh_a
    build:
      context: .
      dockerfile: a/bld.Dockerfile 
      args:
        CONTEXT: a
        #SSHD_CONFIG: sshd_config
        #AUTHORIZED_KEY: ssh/id_ed25519.pub
        #SSH_KEY_DIR: ssh/id_ed25519
    command: /usr/sbin/sshd -D
      
    ports:
      - "2222:22"
    networks: 
      - internal
    volumes: #Host all keys for debugging
      - ./:/home/rta/build:ro
    
  ssh_b:
    hostname: ssh_b
    build:
      context: .
      dockerfile: b/bld.Dockerfile 
      args:
        CONTEXT: b
    command: /usr/sbin/sshd -D
    
    networks:
      - internal





networks:
  internal: {}
