services:
  ssh_a:
    build:
      context: ./bld/a
      args:
        USER: rta 
        #SSHD_CONFIG: sshd_config
        AUTHORIZED_KEY: ssh/id_ed25519.pub
        #SSH_KEY_DIR: ssh/id_ed25519
    ports:
      - "2222:22"
    networks: 
      - internal
    
  ssh_b:
    build:
      context: ./bld/b
      args:
        USER: rta
        #SSHD_CONFIG: sshd_config
        AUTHORIZED_KEY: ssh/id_ed25519.pub
        #SSH_KEY_DIR: ssh/id_ed25519
    networks:
      - internal





networks:
  internal: {}
