services:
  ssh_base:
    build:
      context: .
      dockerfile: Dockerfile 

  ssh_a:
    depends_on:
      - ssh_base
    build:

      context: a
      dockerfile: ../Dockerfile 
      args:
        USER: rta 
        #SSHD_CONFIG: sshd_config
        AUTHORIZED_KEY: ssh/id_ed25519.pub
        #SSH_KEY_DIR: ssh/id_ed25519
    ports:
      - "2222:22"
    networks: 
      - internal
    volumes:
      - ./:/home/rta/build:ro
    
  ssh_b:
    build:
      context: b
      dockerfile: ../Dockerfile 
      args:
        USER: rta
        #SSHD_CONFIG: sshd_config
        AUTHORIZED_KEY: ssh/id_ed25519.pub
        #SSH_KEY_DIR: ssh/id_ed25519
    networks:
      - internal





networks:
  internal: {}
