services:
  ssh_a:
    build:
      context: .
      args:
        USER: rta 
        SSHD_CONFIG: sshd_config
        AUTHORIZED_KEY: ssh/id_ed25519.pub
        PRIV_KEY: ssh/id_ed25519
    ports:
      - "2222:22"
    networks: 
      - internal
    
  ssh_b:
    build:
      context: .
      args:
        USER: rta
        SSHD_CONFIG: sshd_config
        AUTHORIZED_KEY: ssh/id_ed25519.pub
        PRIV_KEY: ssh/id_ed25519
    networks:
      - internal





networks:
  internal: {}
